version: "3.9"

services:
  valletta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valletta
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:YOUR_APP_KEY_HERE
    volumes:
      - storage-data:/var/www/html/storage
      - cache-data:/var/www/html/bootstrap/cache
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.valletta.rule=Host(`${VALLETTA_DOMAIN}`)"
      - "traefik.http.routers.valletta.entrypoints=websecure"
      - "traefik.http.routers.valletta.tls=true"
      - "traefik.http.routers.valletta.tls.certresolver=le"
      - "traefik.http.services.valletta.loadbalancer.server.port=80"

  

volumes:
  storage-data:
  cache-data:


networks:
  proxy:
    external: true
