services:
  valletta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valletta
    restart: unless-stopped
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
    environment:
      - SERVICE_NAME=valletta
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.valletta.rule=Host(`${VALLETTA_DOMAIN}`)"
      - "traefik.http.routers.valletta.entrypoints=websecure"
      - "traefik.http.routers.valletta.tls=true"
      - "traefik.http.routers.valletta.tls.certresolver=le"
      - "traefik.http.services.valletta.loadbalancer.server.port=9000"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  mysql_data:
