
services:
  valletta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valletta
    restart: unless-stopped
    posrt:
      - '9000:9000'
    volumes:
      - .:/var/www
    environment:
      - SERVICE_NAME=valletta
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nest-app.rule=Host(`${VALLETTA_DOMAIN}`)"
      - "traefik.http.routers.nest-app.entrypoints=websecure"
      - "traefik.http.routers.nest-app.tls=true"
      - "traefik.http.routers.nest-app.tls.certresolver=le"

networks:
  proxy:
    name: proxy
    external: true
volumes:
  mysql_data:
